name: lcls-inj-tuning
channels:
  - conda-forge
  - defaults
dependencies:
  - libclang
  - libcblas
  - libxcb
  - gmp
  - glib
  - libgcc-ng
  - cryptography
  - cython
  - gpy
  - libstdcxx-ng
  - pygpu
  - nspr
  - gcc_impl_linux-64
  - tensorflow
  - liblapack
  - python==3.8.8
  - gxx_impl_linux-64
  - gnutls
  - binutils_impl_linux-64
  - mkl
  - pthread-stubs
  - libgomp
  - xz
  - gcc_linux-64
  - libllvm9
  - intel-openmp
  - scikit-learn
  - pytest
  - six
  - libblas
  - openh264
  - zlib
  - threadpoolctl

