name: lcls-inj-tuning
channels:
  - conda-forge
  - default
dependencies:
  - python =3.8
  - numpy =1.19.4
  - matplotlib =3.3.3
  - jupyter =1.0.0
  - pytest =6.2.1
  - jedi =0.17.2
  - dm-tree =0.1.5
  - tensorflow-probability =0.12.1
  - pystan =2.19.1.1
  - scikit-learn ==0.24.2
  - tensorflow ==2.4.1
  - pyepics
  - pip
  - pip:
    - gpflow ==2.1.4
    - scipy ==1.5.4