name: lcls-inj-tuning
channels:
  - conda-forge
  - defaults
dependencies:
  - pysocks
  - parso
  - zlib
  - gst-plugins-base
  - openh264
  - libclang
  - libcblas
  - mako
  - libwebp-base
  - gast
  - dbus
  - testpath
  - tornado
  - olefile
  - wheel
  - packaging
  - paramz
  - readline
  - seaborn-base
  - ld_impl_linux-64
  - sqlite
  - libxcb
  - tensorflow-base
  - brotlipy
  - expat
  - libblas
  - entrypoints
  - gmp
  - joblib
  - fontconfig
  - traitlets
  - wcwidth
  - jupyter_console
  - zeromq
  - libtiff
  - zstd
  - importlib-metadata
  - prompt-toolkit
  - werkzeug
  - glib
  - libssh2
  - prompt_toolkit
  - pyyaml
  - certifi
  - future
  - libffi
  - seaborn
  - krb5
  - binutils_linux-64
  - gstreamer
  - pcre
  - nettle
  - keras-applications
  - libgcc-ng
  - notebook
  - astor
  - pandocfilters
  - nbconvert
  - cryptography
  - ffmpeg
  - libpng
  - jpeg
  - libcurl
  - chardet
  - wrapt
  - six
  - defusedxml
  - gxx_linux-64
  - icu
  - xorg-libxdmcp
  - gettext
  - webencodings
  - lcms2
  - keras
  - ninja
  - pip
  - x264
  - pyglet
  - lz4-c
  - ptyprocess
  - libgpuarray
  - cython
  - ncurses
  - libxkbcommon
  - libiconv
  - cycler
  - gpy
  - libstdcxx-ng
  - pycparser
  - libedit
  - libopenblas
  - typing_extensions
  - xorg-libxau
  - pygpu
  - nspr
  - nss
  - gcc_impl_linux-64
  - libsodium
  - tensorflow
  - patsy
  - widgetsnbextension
  - pickleshare
  - liblapack
  - python==3.8.8
  - gxx_impl_linux-64
  - gnutls
  - pexpect
  - importlib_metadata
  - gym
  - requests
  - binutils_impl_linux-64
  - pyzmq
  - mkl
  - blas
  - mistune
  - idna
  - markupsafe
  - deap
  - zipp
  - grpcio
  - protobuf
  - pthread-stubs
  - decorator
  - libgomp
  - ipython_genutils
  - xz
  - gcc_linux-64
  - backcall
  - mkl-service
  - pygments
  - c-ares
  - libllvm9
  - libuuid
  - ply
  - pyrsistent
  - yaml
  - intel-openmp
  - attrs
  - lame
  - urllib3
  - threadpoolctl
  - cffi
  - libxml2
  - scikit-learn
  - terminado
  - pandoc
  - nbformat
  - termcolor
  - freetype
  - openssl
  - distributed
  - bayesian-optimization
  - typing
  - cothread
  - pytest
  - pip:
    - git+git://github.com/slaclab/edmbutton
    - matlab-wrapper
    - git+git://github.com/slaclab/meme