name: lcls-inj-tuning
channels:
  - conda-forge
  - defaults
dependencies:
  - pysocks
  - parso
  - zlib
  - gst-plugins-base
  - openh264
  - libclang
  - libcblas
  - mako
  - libwebp-base
  - gast
  - olefile
  - wheel
  - packaging
  - paramz
  - ld_impl_linux-64
  - libxcb
  - expat
  - libblas
  - gmp
  - traitlets
  - libtiff
  - zstd
  - importlib-metadata
  - glib
  - libssh2
  - libffi
  - krb5
  - binutils_linux-64
  - gstreamer
  - pcre
  - keras-applications
  - libgcc-ng
  - astor
  - cryptography
  - wrapt
  - six
  - gxx_linux-64
  - icu
  - xorg-libxdmcp
  - lcms2
  - ninja
  - pip
  - x264
  - lz4-c
  - libgpuarray
  - cython
  - ncurses
  - libxkbcommon
  - libiconv
  - cycler
  - gpy
  - libstdcxx-ng
  - pycparser
  - libedit
  - libopenblas
  - typing_extensions
  - xorg-libxau
  - pygpu
  - nspr
  - nss
  - gcc_impl_linux-64
  - libsodium
  - tensorflow
  - patsy
  - widgetsnbextension
  - pickleshare
  - liblapack
  - python==3.8.8
  - gxx_impl_linux-64
  - gnutls
  - pexpect
  - importlib_metadata
  - gym
  - binutils_impl_linux-64
  - mkl
  - blas
  - mistune
  - idna
  - markupsafe
  - deap
  - zipp
  - grpcio
  - pthread-stubs
  - libgomp
  - ipython_genutils
  - xz
  - gcc_linux-64
  - backcall
  - mkl-service
  - c-ares
  - libllvm9
  - libuuid
  - yaml
  - intel-openmp
  - attrs
  - lame
  - threadpoolctl
  - cffi
  - scikit-learn
  - nbformat
  - pytest
