name: lcls-inj-tuning
channels:
  - conda-forge
  - defaults
dependencies:
  - zlib
  - gst-plugins-base
  - openh264
  - libclang
  - libcblas
  - packaging
  - paramz
  - ld_impl_linux-64
  - libxcb
  - expat
  - libblas
  - gmp
  - importlib-metadata
  - glib
  - libssh2
  - libffi
  - krb5
  - binutils_linux-64
  - pcre
  - libgcc-ng
  - cryptography
  - wrapt
  - six
  - gxx_linux-64
  - icu
  - xorg-libxdmcp
  - lcms2
  - ninja
  - pip
  - x264
  - lz4-c
  - cython
  - gpy
  - libstdcxx-ng
  - pycparser
  - libedit
  - libopenblas
  - typing_extensions
  - xorg-libxau
  - pygpu
  - nspr
  - nss
  - gcc_impl_linux-64
  - tensorflow
  - patsy
  - widgetsnbextension
  - pickleshare
  - liblapack
  - python==3.8.8
  - gxx_impl_linux-64
  - gnutls
  - binutils_impl_linux-64
  - mkl
  - markupsafe
  - deap
  - zipp
  - grpcio
  - pthread-stubs
  - libgomp
  - ipython_genutils
  - xz
  - gcc_linux-64
  - mkl-service
  - c-ares
  - libllvm9
  - libuuid
  - intel-openmp
  - threadpoolctl
  - cffi
  - scikit-learn
  - nbformat
  - pytest
