name: lcls-inj-tuning
channels:
  - conda-forge
  - defaults
dependencies:
  - tensorflow
  - python==3.8.8
  #keep
  - gnutls
  # keep
  - mkl
  - libgomp
  #keep
  - xz
  - intel-openmp
  #keep
  - six
  #keep 
  - openh264
  #keep
  - zlib
  - threadpoolctl
  - scikit-learn
  - pytest
