name: lcls-inj-tuning
channels:
  - conda-forge
  - defaults
dependencies:
  - tensorflow
  - python==3.8.8
  #keep
  - gnutls
  #keep
  - mkl
  - intel-openmp
  - threadpoolctl
  - scikit-learn
  - pytest
