name: lcls-inj-tuning
channels:
  - conda-forge
  - defaults
dependencies:
  - libxcb
  - gmp
  - libgcc-ng
  - gpy
  - tensorflow
  - python==3.8.8
  #keep
  - gnutls
  # keep
  - mkl
  - libgomp
  #keep
  - xz
  - intel-openmp
  - scikit-learn
  - pytest
  #keep
  - six
  #keep 
  - openh264
  #keep
  - zlib
  - threadpoolctl
