name: lcls-inj-tuning
channels:
  - conda-forge
dependencies:
  - python =3.8.8
  - gcc_linux-64
  - binutils_impl_linux-64
  - gxx_impl_linux-64
  - libgomp
  - intel-openmp
  - threadpoolctl
  #- numpy =1.19.4
  #- matplotlib =3.3.3
  #- jupyter =1.0.0
  - pytest =6.2.1
  #- jedi =0.17.2
  #- dm-tree =0.1.5
 # - tensorflow-probability =0.12.1
 # - pystan =2.19.1.1
  - tensorflow ==2.4.1
  - scikit-learn ==0.24.2
 # - pyepics
 # - pip
  #- pip:
  #  - gpflow ==2.1.4
  #  - scipy ==1.5.4