name: lcls-inj-tuning
channels:
  - conda-forge
  - default
dependencies:
  - conda-forge::python =3.8
  - conda-forge::numpy =1.19.4
  - conda-forge::matplotlib =3.3.3
  - conda-forge::scikit-learn =0.23.2
  - conda-forge::jupyter =1.0.0
  - conda-forge::pytest =6.2.1
  - conda-forge::jedi =0.17.2
  - conda-forge::dm-tree =0.1.5
  - conda-forge::tensorflow-probability =0.12.1
  - conda-forge::pystan ==2.19.1.1
  - conda-forge::pyepics
  - conda-forge::pip
  - pip:
    - gpflow ==2.1.4
    - scipy ==1.5.4
    - tensorflow ==2.4.0