name: lcls-inj-tuning
channels:
  - conda-forge
  - defaults
dependencies:
  - libclang
  - libcblas
  - ld_impl_linux-64
  - libxcb
  - gmp
  - glib
  - binutils_linux-64
  - libgcc-ng
  - cryptography
  - gxx_linux-64
  - icu
  - xorg-libxdmcp
  - lcms2
  - ninja
  - pip
  - x264
  - lz4-c
  - cython
  - gpy
  - libstdcxx-ng
  - pycparser
  - libedit
  - libopenblas
  - typing_extensions
  - xorg-libxau
  - pygpu
  - nspr
  - nss
  - gcc_impl_linux-64
  - tensorflow
  - patsy
  - widgetsnbextension
  - pickleshare
  - liblapack
  - python==3.8.8
  - gxx_impl_linux-64
  - gnutls
  - binutils_impl_linux-64
  - mkl
  - deap
  - grpcio
  - pthread-stubs
  - libgomp
  - ipython_genutils
  - xz
  - gcc_linux-64
  - mkl-service
  - c-ares
  - libllvm9
  - intel-openmp
  - scikit-learn
  - nbformat
  - pytest
