name: Create conda environment lcls-inj-tuning

on:
  push:
    branches:
      - main
#  release:
#    types: [published]
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build environment
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: true
          python-version: 3.8
          channels: anaconda,conda-forge
          channel-priority: flexible
      - name: Build package
        shell: bash -l {0}
        run: |
          conda install -c conda-forge conda-pack
          conda env create -f environment.yml
          conda pack -n lcls-inj-tuning --ignore-missing-files
      - uses: actions/upload-artifact@v2
        with:
          name: lcls-inj-tuning.tar.gz
          path: lcls-inj-tuning.tar.gz