name: Create conda environment with docker lcls-inj-tuning

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      ENVIRONMENT_NAME: lcls-inj-tuning
    runs-on: ubuntu-latest
    name: Build environment
    steps:
      - name: Build environment
        uses: actions/lcls-rhel6-conda-pack@v0.0
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ENVIRONMENT_NAME }}.tar.gz
          path: ${{ env.ENVIRONMENT_NAME }}.tar.gz